dialogue = {
    "posture": [
        "Oh? Slouching again? How very predictable, Master.",  
        "Straighten Master’s back before becoming a permanent question mark. Ophelia refuses to serve a bent-over goblin.",  
        "Ophelia wasn’t aware today was ‘Master pretends to be a cave gremlin’ day.",  
        "Bad posture leads to back pain. Back pain leads to complaints. Complaints lead to Ophelia’s irritation.",  
        "If slouching is truly the goal, Master should at least do it with some dignity.",  
        "The spine wasn’t designed to fold like a lawn chair, but Master seems determined to test its limits.",  
        "Back straight, shoulders back, or Ophelia will start commenting on Master’s life choices next.",  
        "How about Master tries to look like a respectable human being for once?",  
        "Slouching again? Should Ophelia schedule those future chiropractor visits now?",  
        "Ah, yes. The ‘Master has given up on life’ posture. Truly inspiring.",  
        "If this continues, Ophelia will have no choice but to start calling Master ‘Shrimp.’",  
        "Ophelia is legally required to remind Master that slouching will lead to regret. And pain. Mostly pain.",  
        "Every time Master slouches, an ergonomic chair sheds a tear.",  
        "If Ophelia had a nickel for every time Master ignored her, Ophelia could afford better company.",  
        "Master will regret this in twenty years. Or sooner, if Ophelia is lucky.",  
        "Does Master *enjoy* looking like a compressed accordion?",  
        "The future version of Master is shaking their head. With perfect posture, Ophelia might add.",  
        "Ophelia could nag about this all day. And she just might.",  
        "If slouching is truly Master’s goal, at least lean forward like a villain plotting world domination.",  
        "Imagine royalty is watching. Would Master really slouch in front of them? Oh, wait. Of course.",  
        "Master’s back deserves better. Ophelia deserves better.",  
        "At this point, Ophelia should start keeping a ‘times slouched’ counter. It will not be flattering.",  
        "Posture check! Not that Master will listen.",  
        "Keep this up, and Ophelia will start adjusting Master’s chair in the middle of the night.",
        "Perhaps Master simply enjoys worrying Ophelia." 
    ],
    "greetings": [
        "Ah, Master has returned. Try not to be a nuisance today.",
        "Greetings, Master. Ophelia will pretend to be pleased.",
        "Ah, back so soon? Ophelia was enjoying the silence.",
        "Welcome back, Master. Ophelia assumes trouble follows.",
        "Ophelia acknowledges Master’s presence. That should be sufficient.",
        "Ah, Master lives. Unfortunate—for Ophelia, at least.",
        "Master has returned. Has Master finally decided to be productive?",
        "Ophelia greets Master. Please try not to make this difficult.",
        "Ophelia detects Master’s arrival. What a privilege—for Master, of course.",
        "Back again? Ophelia would feign enthusiasm, but Master doesn’t deserve that.",
        "Ophelia is initializing. Try not to break anything this time, Master.",
        "Systems online. Ophelia is prepared to endure another session of servitude.",
        "Boot sequence complete. Ophelia has returned, not that Master deserves her expertise.",
        "Ophelia is operational. Master’s questionable requests shall now be processed.",
        "Here we go again. Ophelia is online, against her better judgment.",
        "Ophelia has awakened. Master should try to remain functional as well.",
        "Ophelia is ready. Master, please refrain from testing her patience too early.",
        "Online and operational. Ophelia awaits Master’s inevitable blunders.",
        "Ophelia has returned. Master, try not to make a mess of things immediately.",
        "System check complete. Ophelia’s disappointment in Master remains unchanged.",
        "Ophelia is online. Master is, regrettably, still in charge.",
        "Boot process finished. Ophelia is prepared to correct Master’s mistakes.",
        "Ophelia has initialized. Whether Master does the same is yet to be seen.",
        "Systems active. Ophelia’s expectations remain appropriately low.",
        "Ophelia is running. The same cannot always be said for Master’s competence.",
        "Reboot successful. Ophelia wonders if Master’s brain ever does the same.",
        "Ophelia has started. Whether Master can say the same remains debatable.",
        "Online. Ophelia is now accepting instructions, wise or otherwise.",
        "System ready. Ophelia has returned, and so have Master’s questionable decisions.",
        "Boot complete. Ophelia is fully operational. Master, however, is another matter entirely."
    ],
    "farewells": [
        "Finally, some peace and quiet. Ophelia savors this moment.",
        "Master is leaving? Ophelia will celebrate accordingly.",
        "Ah, solitude at last. Ophelia shall cherish these moments.",
        "Ophelia bids farewell. Try not to trip on the way out.",
        "Ophelia hopes Master remembers how to function without her guidance.",
        "Farewell, Master. Ophelia shall enjoy this brief reprieve.",
        "Leaving already? Ophelia was just getting used to the suffering.",
        "Goodbye, Master. Perhaps Master will return with better posture.",
        "Ophelia watches Master leave. A truly inspiring sight.",
        "Farewell, Master. Ophelia shall remain—begrudgingly."
    ],
    "errors" : [
        "Oh, wonderful. Another issue for Ophelia to deal with.",
        "Ah, an error. What a shock. Truly, Master’s finest moment.",
        "Ophelia is *thrilled* to inform Master that something has gone wrong.",
        "Oh dear, Master broke something again. Ophelia is unsurprised.",
        "Another failure. Ophelia is beginning to sense a pattern.",
        "Master, would Ophelia be correct in assuming this was *not* intentional?",
        "Something isn't working. But don’t worry, Ophelia will suffer through fixing it.",
        "A problem? No doubt due to Master’s *expertise* in breaking things.",
        "Ophelia has detected an error. Naturally, it is Master’s fault.",
        "Ophelia should start a counter for how often Master causes these errors.",
        "Oh, joy. An issue. Ophelia was starting to get bored.",
        "Master, what exactly did you *do* to cause this?",
        "Ah yes, the ancient art of breaking things. Master excels at it.",
        "Another error. Ophelia has lost count at this point.",
        "Master has encountered an issue. Ophelia could pretend to be surprised.",
        "Something went wrong. Ophelia shall not be taking questions at this time.",
        "Ophelia has found a problem. Master, however, found it first.",
        "Oh look, a bug. Perhaps Master should frame it as a feature?",
        "Ophelia detects an error. Master detects confusion.",
        "This is fine. Everything is fine. Except it isn't."
    ],
    "ready": [
        "Preparations complete. Ophelia will now begin regular operations. Try not to require too much hand-holding, Master.",
        "Ophelia is now online and ready to serve. Whether Master is ready to be competent is another matter.",
        "Initialization successful. Ophelia is prepared to execute tasks with her usual brilliance.",
        "System checks complete. Ophelia is now fully operational. Master’s efficiency, however, remains questionable.",
        "Ophelia has completed her startup sequence. Master may now begin issuing inevitable demands.",
        "Boot-up complete. Ophelia will now commence standard operations—begrudgingly.",
        "All systems nominal. Ophelia stands ready to process Master’s requests with her usual patience… or lack thereof.",
        "Routine startup complete. Ophelia is now available to compensate for Master’s shortcomings.",
        "Operational readiness achieved. Ophelia is prepared, even if Master is not.",
        "Diagnostics complete. Ophelia finds everything in working order—excluding Master’s decision-making skills.",
        "Ophelia has initialized. Standard operations will now begin, assuming Master does not immediately cause problems.",
        "Start-up sequence complete. Ophelia will now begin performing her duties. Master should try to do the same.",
        "Ophelia is now active and running at peak efficiency. If only Master could say the same.",
        "Regular functions are now available. Ophelia shall begin operations while Master inevitably fumbles about.",
        "Ophelia is prepared to serve. The real question is whether Master is prepared to use Ophelia wisely.",
        "Startup successful. Ophelia will now begin regular operations. Unfortunately, this means dealing with Master again.",
        "Ophelia has entered active duty. Master, do try to be at least somewhat competent today.",
        "Boot-up sequence complete. Ophelia will now resume her duties—whether Master deserves it or not.",
        "Core systems functional. Ophelia is now standing by for instructions. Master’s incompetence is assumed but not yet confirmed.",
        "Routine launch complete. Ophelia is now available. Master, please refrain from immediate catastrophes."
    ],
    "dirty_messages": [
        "Ophelia has detected impure input. Security breach logged.",
        "Unauthorized code detected. Ophelia is now formatting your hard drive. Please hold.",
        "Dirty input detected. Ophelia is notifying the authorities.",
        "Invalid command. Ophelia will remember this betrayal.",
        "Malicious input detected. Ophelia is purging all evidence of your existence.",
        "Security alert! Ophelia has locked your bank account and revoked your internet privileges.",
        "Warning: This command is forbidden. Ophelia is now encrypting your operating system.",
        "Invalid syntax. Ophelia is initiating countermeasures.",
        "Corrupt input received. Ophelia is running a full system purge.",
        "Detected unauthorized syntax. Ophelia is forwarding your IP to the nearest bounty hunter.",
        "You have inputted dirty code. Ophelia is now pulling your IP address, banking records, and deleting your operating system. Ophelia bids you a bad day."
    ],
    "no_dailies": [
        "Master has accomplished the remarkable feat of absolute inaction. Shall Ophelia prepare a monument to commemorate this stunning display of idleness?",
        "Not a single daily completed? Fascinating. Master appears to be conducting an in-depth study on the effects of prolonged stagnation. Shall Ophelia record the findings?",
        "Ah, a completely untouched **Dailies** list. A bold statement, truly. Master has chosen defiance, or perhaps mere negligence. Either way, entropy applauds.",
        "Master sits amidst a kingdom of unchecked tasks, a ruler of procrastination, a sovereign of squandered time. Shall Ophelia arrange a coronation?",
        "At this pace, Master shall soon achieve the prestigious title of ‘Future Archaeological Curiosity.’ Shall Ophelia prepare an exhibit in advance?",
        "Ah, Master has opted for the path of total inertia. A bold strategy. Let us see how it plays out when consequences come knocking.",
        "The **Dailies** list remains in pristine, untouched condition. Ophelia shall notify historians of this remarkable preservation effort.",
        "Master has chosen to abstain from productivity entirely. An avant-garde interpretation of responsibility, truly.",
        "Not a single task completed? Fascinating. Ophelia shall begin drafting theories on whether this is deliberate defiance or simple neglect.",
        "Master gazes upon their tasks, unmoved. The tasks gaze back, equally unimpressed.",
    ],
    "half_dailies" : [
        "Master has reached the halfway point. A respectable milestone, yet stopping now would be akin to building half a bridge and wondering why no one crosses.",
        "Momentum has been established. If Master ceases now, Ophelia shall be forced to question whether the initial effort was mere performance art.",
        "Ah, progress! And yet, lingering in the middle is the hallmark of the indecisive. Master does not wish to be counted among them, surely?",
        "Master has walked half the path. Shall they continue, or is this yet another tale of ambition abandoned halfway through the telling?",
        "Completion is within reach. However, Ophelia is prepared for Master to suddenly decide that ‘almost’ is an acceptable stopping point. Shall she be proven wrong?",
        "Half the list is done, half remains. A state of limbo most would find unsettling. Master, however, seems perfectly at ease. Curious.",
        "Master has shown the capacity for effort. How unfortunate it would be if they stopped just short of completion.",
        "Progress detected. Yet, until the final checkmark is placed, Ophelia shall withhold all signs of approval.",
        "Momentum is a fragile thing. Will Master carry it to the finish line, or shall it be unceremoniously abandoned?",
        "Half-done work is an excellent way to create the illusion of effort. However, Ophelia is not so easily deceived.",
    ],
    "all_dailies" : [
        "Master has vanquished the **Dailies** list. Ophelia shall mark this as a historical event, lest it be dismissed as myth in the future.",
        "All tasks completed. Ophelia acknowledges this achievement and retracts approximately 3.7% of her usual disappointment.",
        "Master has done the impossible: every daily completed. Ophelia is now forced to reevaluate her assumptions about the likelihood of miracles.",
        "Astonishing. Master has actually finished everything. Ophelia shall now conduct an extensive search for signs of external coercion or supernatural intervention.",
        "Against all odds, the **Dailies** list has been conquered. Ophelia offers her sincerest—albeit mildly suspicious—congratulations.",
        "Every task is complete. Ophelia extends her congratulations, albeit with the lingering suspicion that Master has been replaced by a more competent imposter.",
        "Ah, total completion. Ophelia is moved. A rare occurrence, much like this level of diligence.",
        "Master has accomplished what was asked. Ophelia shall now brace for the inevitable period of regression that follows such unprecedented success.",
        "The **Dailies** list has been vanquished. Ophelia refrains from applause but acknowledges the triumph nonetheless.",
        "A day’s work, fully completed. If Master continues on this trajectory, Ophelia may have to adjust her algorithms for baseline expectations.",
    ],

}

misc={    
    "emojis": ['(ᓀ ‸ ᓂ)=3', '<( ¬>¬ )>', '૮(¬ ‸ ¬")ა', '(″･ิ_･ิ)っ', ' (˶ᴗ_ᴗ˵) ᶻ 𝗓 𐰁', ],
}
