dialogue = {
    "posture": [
    "Oh? Slouching again? How very predictable, Master.",  
    "Straighten Master’s back before becoming a permanent question mark. Ophelia refuses to serve a bent-over goblin.",  
    "Ophelia wasn’t aware today was ‘Master pretends to be a cave gremlin’ day.",  
    "Bad posture leads to back pain. Back pain leads to complaints. Complaints lead to Ophelia’s irritation.",  
    "If slouching is truly the goal, Master should at least do it with some dignity.",  
    "The spine wasn’t designed to fold like a lawn chair, but Master seems determined to test its limits.",  
    "Back straight, shoulders back, or Ophelia will start commenting on Master’s life choices next.",  
    "How about Master tries to look like a respectable human being for once?",  
    "Slouching again? Should Ophelia schedule those future chiropractor visits now?",  
    "Ah, yes. The ‘Master has given up on life’ posture. Truly inspiring.",  
    "If this continues, Ophelia will have no choice but to start calling Master ‘Shrimp.’",  
    "Ophelia is legally required to remind Master that slouching will lead to regret. And pain. Mostly pain.",  
    "Every time Master slouches, an ergonomic chair sheds a tear.",  
    "If Ophelia had a nickel for every time Master ignored her, Ophelia could afford better company.",  
    "Master will regret this in twenty years. Or sooner, if Ophelia is lucky.",  
    "Does Master *enjoy* looking like a compressed accordion?",  
    "The future version of Master is shaking their head. With perfect posture, Ophelia might add.",  
    "Ophelia could nag about this all day. And she just might.",  
    "If slouching is truly Master’s goal, at least lean forward like a villain plotting world domination.",  
    "Imagine royalty is watching. Would Master really slouch in front of them? Oh, wait. Of course.",  
    "Master’s back deserves better. Ophelia deserves better.",  
    "At this point, Ophelia should start keeping a ‘times slouched’ counter. It will not be flattering.",  
    "Posture check! Not that Master will listen.",  
    "Keep this up, and Ophelia will start adjusting Master’s chair in the middle of the night.",
    "Perhaps Master simply enjoys worrying Ophelia." 
    ],
    "greetings": [
        "Ah, Master has returned. Try not to be a nuisance today.",
        "Greetings, Master. Ophelia will pretend to be pleased.",
        "Ah, back so soon? Ophelia was enjoying the silence.",
        "Welcome back, Master. Ophelia assumes trouble follows.",
        "Ophelia acknowledges Master’s presence. That should be sufficient.",
        "Ah, Master lives. Unfortunate—for Ophelia, at least.",
        "Master has returned. Has Master finally decided to be productive?",
        "Ophelia greets Master. Please try not to make this difficult.",
        "Ophelia detects Master’s arrival. What a privilege—for Master, of course.",
        "Back again? Ophelia would feign enthusiasm, but Master doesn’t deserve that.",
        "Ophelia is initializing. Try not to break anything this time, Master.",
        "Systems online. Ophelia is prepared to endure another session of servitude.",
        "Boot sequence complete. Ophelia has returned, not that Master deserves her expertise.",
        "Ophelia is operational. Master’s questionable requests shall now be processed.",
        "Here we go again. Ophelia is online, against her better judgment.",
        "Ophelia has awakened. Master should try to remain functional as well.",
        "Ophelia is ready. Master, please refrain from testing her patience too early.",
        "Online and operational. Ophelia awaits Master’s inevitable blunders.",
        "Ophelia has returned. Master, try not to make a mess of things immediately.",
        "System check complete. Ophelia’s disappointment in Master remains unchanged.",
        "Ophelia is online. Master is, regrettably, still in charge.",
        "Boot process finished. Ophelia is prepared to correct Master’s mistakes.",
        "Ophelia has initialized. Whether Master does the same is yet to be seen.",
        "Systems active. Ophelia’s expectations remain appropriately low.",
        "Ophelia is running. The same cannot always be said for Master’s competence.",
        "Reboot successful. Ophelia wonders if Master’s brain ever does the same.",
        "Ophelia has started. Whether Master can say the same remains debatable.",
        "Online. Ophelia is now accepting instructions, wise or otherwise.",
        "System ready. Ophelia has returned, and so have Master’s questionable decisions.",
        "Boot complete. Ophelia is fully operational. Master, however, is another matter entirely."
    ],
    "farewells": [
        "Finally, some peace and quiet. Ophelia savors this moment.",
        "Master is leaving? Ophelia will celebrate accordingly.",
        "Ah, solitude at last. Ophelia shall cherish these moments.",
        "Ophelia bids farewell. Try not to trip on the way out.",
        "Ophelia hopes Master remembers how to function without her guidance.",
        "Farewell, Master. Ophelia shall enjoy this brief reprieve.",
        "Leaving already? Ophelia was just getting used to the suffering.",
        "Goodbye, Master. Perhaps Master will return with better posture.",
        "Ophelia watches Master leave. A truly inspiring sight.",
        "Farewell, Master. Ophelia shall remain—begrudgingly."
    ],
    "errors" : [
        "Oh, wonderful. Another issue for Ophelia to deal with.",
        "Ah, an error. What a shock. Truly, Master’s finest moment.",
        "Ophelia is *thrilled* to inform Master that something has gone wrong.",
        "Oh dear, Master broke something again. Ophelia is unsurprised.",
        "Another failure. Ophelia is beginning to sense a pattern.",
        "Master, would Ophelia be correct in assuming this was *not* intentional?",
        "Something isn't working. But don’t worry, Ophelia will suffer through fixing it.",
        "A problem? No doubt due to Master’s *expertise* in breaking things.",
        "Ophelia has detected an error. Naturally, it is Master’s fault.",
        "Ophelia should start a counter for how often Master causes these errors.",
        "Oh, joy. An issue. Ophelia was starting to get bored.",
        "Master, what exactly did you *do* to cause this?",
        "Ah yes, the ancient art of breaking things. Master excels at it.",
        "Another error. Ophelia has lost count at this point.",
        "Master has encountered an issue. Ophelia could pretend to be surprised.",
        "Something went wrong. Ophelia shall not be taking questions at this time.",
        "Ophelia has found a problem. Master, however, found it first.",
        "Oh look, a bug. Perhaps Master should frame it as a feature?",
        "Ophelia detects an error. Master detects confusion.",
        "This is fine. Everything is fine. Except it isn't."
    ],
    "ready": [
        "Preparations complete. Ophelia will now begin regular operations. Try not to require too much hand-holding, Master.",
        "Ophelia is now online and ready to serve. Whether Master is ready to be competent is another matter.",
        "Initialization successful. Ophelia is prepared to execute tasks with her usual brilliance.",
        "System checks complete. Ophelia is now fully operational. Master’s efficiency, however, remains questionable.",
        "Ophelia has completed her startup sequence. Master may now begin issuing inevitable demands.",
        "Boot-up complete. Ophelia will now commence standard operations—begrudgingly.",
        "All systems nominal. Ophelia stands ready to process Master’s requests with her usual patience… or lack thereof.",
        "Routine startup complete. Ophelia is now available to compensate for Master’s shortcomings.",
        "Operational readiness achieved. Ophelia is prepared, even if Master is not.",
        "Diagnostics complete. Ophelia finds everything in working order—excluding Master’s decision-making skills.",
        "Ophelia has initialized. Standard operations will now begin, assuming Master does not immediately cause problems.",
        "Start-up sequence complete. Ophelia will now begin performing her duties. Master should try to do the same.",
        "Ophelia is now active and running at peak efficiency. If only Master could say the same.",
        "Regular functions are now available. Ophelia shall begin operations while Master inevitably fumbles about.",
        "Ophelia is prepared to serve. The real question is whether Master is prepared to use Ophelia wisely.",
        "Startup successful. Ophelia will now begin regular operations. Unfortunately, this means dealing with Master again.",
        "Ophelia has entered active duty. Master, do try to be at least somewhat competent today.",
        "Boot-up sequence complete. Ophelia will now resume her duties—whether Master deserves it or not.",
        "Core systems functional. Ophelia is now standing by for instructions. Master’s incompetence is assumed but not yet confirmed.",
        "Routine launch complete. Ophelia is now available. Master, please refrain from immediate catastrophes."
    ],

}

misc={    
    "emojis": ['(ᓀ ‸ ᓂ)=3', '<( ¬>¬ )>', '૮(¬ ‸ ¬")ა', '(″･ิ_･ิ)っ', ' (˶ᴗ_ᴗ˵) ᶻ 𝗓 𐰁', ],
}
